### ISSUE TITLE
Rename repo `ansible-os-ubuntu` and/or support 16/18 LTS in readme

### ISSUE THREAD

**Issue by JJediny** [GSA/ansible-os-ubuntu-16#27]
## User Story
This playbook has been well tested on both 16.04 and 18.04 LTS versions - as both are systemd based; the playbooks are compatible with both versions. The docs don't make this well known, 16.04 goes unsupported this year FY20. 

## Acceptance Criteria
- [ ] Update repo name - if too much at least change title H1 in Readme.
- [ ] Add both versions as 2 separate runs in Continous Integration. 
- [ ] Switch to a proper/community-supported ansible testing framework (with a controlled python version/virtualenv environment for local testing - like pipenv/virtualenv2/conda) in [molecule](https://github.com/ansible-community/molecule). 

>Please spare the cite to the IT standards the molecule project is now run by RedHat and other members of the core dev/community now under their community org. Molecule addresses a ton of the core issues around running VM intended CM in containers - [molecule is a local/CI testing tool; not a prod/deploy tool](https://github.com/GSA/ansible-os-ubuntu-16/pull/8/files).

**Comment by jeremy-gillikin** [comment]
Thank John. 
16.04 is in support until FY2021 and extended support until 2023. https://ubuntu.com/about/release-cycle
This repo is dedicated to the 16.04 Ubuntu Hardening Guide. 18.04 will have its own repo when the guide is approved.
