### ISSUE TITLE
Idempotence test failed because of the following tasks

### ISSUE THREAD

**Issue by JJediny** [GSA/ansible-os-ubuntu-16#6]
ERROR: Idempotence test failed because of the following tasks:

- [ ] * [xenial] => ansible-os-ubuntu-16 : 1.5.1 | Ensure core dumps are restricted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 1.5.1 | Ensure core dumps are restricted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.1.2 | Ensure packet redirect sending is disabled
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.1.2 | Ensure packet redirect sending is disabled
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.1.2 | Ensure packet redirect sending is disabled
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.1.2 | Ensure packet redirect sending is disabled
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.2.1 | Ensure source routed packets are not accepted
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.2.1 | Ensure source routed packets are not accepted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.2.2 | Ensure ICMP redirects are not accepted
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.2.2 | Ensure ICMP redirects are not accepted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.2.3 | Ensure secure ICMP redirects are not accepted
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.2.3 | Ensure secure ICMP redirects are not accepted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.2.4 | Ensure suspicious packets are logged
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.2.4 | Ensure suspicious packets are logged
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.3.1 | Ensure IPv6 router advertisements are not accepted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.3.1 | Ensure IPv6 router advertisements are not accepted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 3.3.2 | Ensure IPv6 redirects are not accepted
- [ ] * [xenial] => ansible-os-ubuntu-16 : 3.3.2 | Ensure IPv6 redirects are not accepted
- [ ] * [bionic] => ansible-os-ubuntu-16 : 5.1.8 | Ensure at/cron is restricted to authorized users
- [ ] * [xenial] => ansible-os-ubuntu-16 : 5.1.8 | Ensure at/cron is restricted to authorized users
- [ ] * [bionic] => ansible-os-ubuntu-16 : 5.4.3 | Ensure default group for the root account is GID 0
- [ ] * [xenial] => ansible-os-ubuntu-16 : 5.4.3 | Ensure default group for the root account is GID 0

**Comment by doug-sillex** [comment]
Closing due to added idempotent check and recent updates
