### ISSUE TITLE
Setup Molecule testing for ansible role for Ubuntu 16/18 for Continuous Integration

### ISSUE THREAD

**Issue by JJediny** [GSA/ansible-os-ubuntu-16#7]
@jeremy-gillikin can you enable circleci for this repository or give me owner rights? Would like to make a PR for this as a starting point for our programs switch from Ubuntu 14 to 16/18
https://github.com/JJediny/ansible-os-ubuntu-16/pull/1

**Comment by jeremy-gillikin** [comment]
Hello @JJediny We plan on adding circle to all our repos within the week or so. We will also be making updates and enhancements as well.

**Comment by JJediny** [comment]
Created https://github.com/GSA/ansible-os-ubuntu-16/pull/8 as a starting point for CI. Because circleci only allows for running unprivileged containers, tasks that alter grub/systemd/sysctl/ssh had to be tagged as not tested for now. There is also a fair bit of linting and idempotence work to enable anything with the `# to fix`. I can also add a VirtualBox driver for molecule?

**Comment by doug-sillex** [comment]
Closing due to significant recent updates
